WIFI_SSID = 'XXXXXXX'
WIFI_PASS = 'XXXXXXX'

UBIDOTS_TOKEN = 'BBFF-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' # Not API-token
UBIDOTS_MQTT_URL = 'industrial.api.ubidots.com'
UBIDOTS_MQTT_PORT = 1883
UBIDOTS_MQTT_TOPIC = '/v1.6/devices/'
